site_name: Юнак

theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  custom_dir: overrides
  palette:
    primary: white
  features:
    - navigation.indexes

plugins:
  - blog:
      blog_dir: .
      archive: false
  - search

nav:
  - Нататкі: 
    - 'index.md'
  - Школа юных матэматыкаў:
    - 'school/index.md'
    - 'school/fall_2023.md'

extra_css:
  - css/extra.css


